format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """
$cmd_duration\
$time\
"""

[directory]
style = "blue"

[character]
success_symbol = '[\$](green)'
error_symbol = '[\$](red)'
vimcmd_symbol = '[:](purple)'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style) "
style = "cyan"
conflicted = "c"
untracked = "u"
modified = "m"
staged = "s"
renamed = "r"
deleted = "d"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# [python]
# format = "[$virtualenv]($style) "
# style = "bright-black"

[time]
disabled = false
format = '[$time]($style)'
style = "bright-black"
